name: 📼 On Demand Support
description: Bug/issue realted to on demand
title: '[issue]<title>'
labels: ['On Demand: bug', 'prod success incident']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this support form! The more info you provide, the more we can help you.

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: dropdown
    attributes:
      label: Issue
      description: What aspect of On Demand is the issue related to?
      options:
        - On Demand API
        - On Demand SDK
        - Playback
        - Token-gating
        - Other
    validations:
      required: true

  - type: input
    attributes:
      label: Asset ID
    validations:
      required: true

  - type: input
    attributes:
      label: Playback URL
      placeholder: https://lp-playback.com/hls/<playbackId>/index.m3u8
    validations:
      required: false

  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps or code snippets to reproduce the behavior.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Provide the error message from issue
      description: |
        This makes investigating issues and helping you out significantly easier! For most issues, you will likely get asked to provide one so why not add one now :)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Browser info? Screenshots? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false